# Generated by Django 5.1.4 on 2025-02-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0003_provider_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='discount_coupon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
