# Generated by Django 5.1.4 on 2025-02-22 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0004_subscription_discount_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(help_text='Fully Qualified Domain Name (FQDN)', max_length=255, unique=True)),
                ('domain_type', models.CharField(choices=[('.com', '.com'), ('.in', '.in')], max_length=255)),
                ('ssl_certification', models.BooleanField(default=False, help_text='Indicates if SSL is enabled for the domain')),
                ('ssl_expiry_date', models.DateField(blank=True, help_text='SSL certificate expiration date', null=True)),
                ('whois_protection', models.BooleanField(default=False, help_text='WHOIS privacy protection enabled or not')),
                ('domain_transfer_status', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked'), ('pending_transfer', 'Pending Transfer')], default='locked', help_text='Current status of domain transfer', max_length=50)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domain', to='SubSync.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=255)),
                ('server_type', models.CharField(choices=[('In-house', 'In-house'), ('External', 'External')], max_length=50)),
                ('server_capacity', models.PositiveIntegerField(default=0, help_text='Total resource capacity (e.g., CPU, RAM, storage).')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='server', to='SubSync.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareSubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('license_type', models.CharField(max_length=255)),
                ('no_of_users', models.PositiveIntegerField(default=1)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='software_detail', to='SubSync.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_type', models.CharField(choices=[('Prepaid', 'Prepaid'), ('Postpaid', 'Postpaid')], max_length=50)),
                ('utility_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='SubSync.subscription')),
            ],
        ),
    ]
