# Generated by Django 5.1.4 on 2025-02-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0005_domain_servers_softwaresubscriptions_utilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilities',
            name='utility_type',
            field=models.CharField(choices=[('Internet', 'Internet'), ('Mobile', 'Mobile'), ('Electricity', 'Electricity'), ('Water', 'Water')], max_length=50),
        ),
    ]
