# Generated by Django 5.1.4 on 2025-02-25 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0006_alter_utilities_utility_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_name', models.CharField(max_length=100)),
                ('hardware_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('server', 'Server'), ('router', 'Router'), ('switch', 'Switch'), ('modem', 'Modem'), ('firewall', 'Firewall'), ('printer', 'Printer'), ('scanner', 'Scanner'), ('ups', 'UPS'), ('cooling_unit', 'Cooling Unit'), ('iot_device', 'IoT Device'), ('other', 'Other')], max_length=50)),
                ('manufacturer', models.CharField(max_length=255)),
                ('model_number', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('assigned_department', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hardware',
            },
        ),
        migrations.CreateModel(
            name='HardwareService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_provider', models.CharField(max_length=100)),
                ('service_provider_contact', models.CharField(max_length=100)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('service_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_services_done', models.IntegerField(default=0)),
                ('no_of_free_services', models.IntegerField(default=0)),
                ('free_services_used', models.IntegerField(default=0)),
                ('service_period', models.IntegerField(default=180, help_text='Service interval in days')),
                ('hardware', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='SubSync.hardware')),
            ],
            options={
                'db_table': 'hardware_service',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_type', models.CharField(max_length=50)),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('hardware', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='SubSync.hardware')),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_provider', models.CharField(max_length=100)),
                ('warranty_period', models.IntegerField(help_text='Warranty period in months')),
                ('warranty_expiry_date', models.DateField()),
                ('is_extended_warranty', models.BooleanField(default=False)),
                ('extended_period', models.IntegerField(blank=True, help_text='Extended warranty period in months', null=True)),
                ('hardware', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warranty', to='SubSync.hardware')),
            ],
            options={
                'db_table': 'warranty',
            },
        ),
    ]
