# Generated by Django 5.1.4 on 2025-03-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0008_rename_subscription_id_subscription_subscription_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Unpaid', 'Unpaid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Canceled', 'Canceled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_category',
            field=models.CharField(choices=[('Software', 'Software'), ('Billing', 'Billing'), ('Server', 'Server'), ('Domain', 'Domain')], max_length=50),
        ),
    ]
