# Generated by Django 5.1.4 on 2025-03-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0011_alter_reminder_notification_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwaresubscriptions',
            name='license_key',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_id',
        ),
        migrations.AddField(
            model_name='domain',
            name='domain_id',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='softwaresubscriptions',
            name='software_id',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilities',
            name='consumer_id',
            field=models.IntegerField(default=43),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_time',
            field=models.TimeField(default='11:30:00', help_text='Time to send the reminder.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('database', 'Database'), ('compute', 'Compute'), ('storage', 'Storage'), ('network', 'Network'), ('website', 'Website')], max_length=50),
        ),
    ]
