# Generated by Django 5.1.4 on 2025-03-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0012_remove_softwaresubscriptions_license_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_time',
        ),
    ]
