# Generated by Django 5.1.4 on 2025-03-12 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0013_remove_reminder_reminder_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilities',
            old_name='consumer_id',
            new_name='consumer_no',
        ),
    ]
