# Generated by Django 5.1.4 on 2025-03-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0014_rename_consumer_id_utilities_consumer_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='server_capacity',
            field=models.CharField(max_length=255),
        ),
    ]
