# Generated by Django 5.1.4 on 2025-03-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0015_alter_servers_server_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwaresubscriptions',
            name='software_id',
            field=models.CharField(),
        ),
    ]
