# Generated by Django 5.1.4 on 2025-03-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0016_alter_softwaresubscriptions_software_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
            preserve_default=False,
        ),
    ]
