# Generated by Django 5.1.4 on 2025-03-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0017_customer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardware',
            name='hardware_name',
        ),
        migrations.RemoveField(
            model_name='hardwareservice',
            name='free_services_used',
        ),
        migrations.RemoveField(
            model_name='hardwareservice',
            name='no_of_free_services',
        ),
        migrations.RemoveField(
            model_name='hardwareservice',
            name='no_of_services_done',
        ),
        migrations.RemoveField(
            model_name='hardwareservice',
            name='service_period',
        ),
        migrations.RemoveField(
            model_name='hardwareservice',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='hardwareservice',
            name='service_provider_contact',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_type',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='supplier_contact',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='warranty',
            name='warranty_period',
        ),
        migrations.RemoveField(
            model_name='warranty',
            name='warranty_provider',
        ),
        migrations.AddField(
            model_name='hardware',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hardwareservice',
            name='last_free_service_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
