# Generated by Django 5.1.4 on 2025-03-15 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0018_remove_hardware_hardware_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardwareservice',
            old_name='last_free_service_date',
            new_name='free_service_until',
        ),
        migrations.RemoveField(
            model_name='warranty',
            name='extended_period',
        ),
        migrations.AddField(
            model_name='hardwareservice',
            name='next_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hardwareservice',
            name='service_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hardwareservice',
            name='service_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warranty',
            name='extended_warranty_period',
            field=models.IntegerField(blank=True, choices=[(1, '1 Year'), (2, '2 Years'), (3, '3 Years'), (5, '5 Years')], null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hardware_type',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Mobile Phone', 'Mobile Phone'), ('Tablet', 'Tablet'), ('Network Device', 'Network Device'), ('Air Conditioner', 'Air Conditioner'), ('Server', 'Server'), ('Printer', 'Printer'), ('Scanner', 'Scanner'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='hardwareservice',
            name='hardware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='SubSync.hardware'),
        ),
        migrations.AlterField(
            model_name='hardwareservice',
            name='service_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterModelTable(
            name='hardwareservice',
            table=None,
        ),
        migrations.AlterModelTable(
            name='purchase',
            table=None,
        ),
        migrations.AlterModelTable(
            name='warranty',
            table=None,
        ),
        migrations.CreateModel(
            name='AirConditioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btu_rating', models.CharField(max_length=100)),
                ('energy_rating', models.CharField(max_length=100)),
                ('hardware', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='air_conditioner', to='SubSync.hardware')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_type', models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop')], max_length=50)),
                ('cpu', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('hardware', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='computer', to='SubSync.hardware')),
            ],
        ),
        migrations.CreateModel(
            name='HardwareServers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('storage_configuration', models.CharField(max_length=100)),
                ('operating_system', models.CharField(max_length=100)),
                ('hardware', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='server', to='SubSync.hardware')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throughput', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('hardware', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network_device', to='SubSync.hardware')),
            ],
        ),
        migrations.CreateModel(
            name='PortableDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('Mobile Phone', 'Mobile Phone'), ('Tablet', 'Tablet')], max_length=50)),
                ('os_version', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('imei_number', models.CharField(blank=True, max_length=100, null=True)),
                ('hardware', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portable_device', to='SubSync.hardware')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_technology', models.CharField(max_length=100)),
                ('print_speed', models.CharField(max_length=100)),
                ('connectivity', models.CharField(max_length=100)),
                ('hardware', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='printer', to='SubSync.hardware')),
            ],
        ),
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_resolution', models.CharField(max_length=100)),
                ('scan_type', models.CharField(max_length=100)),
                ('connectivity', models.CharField(max_length=100)),
                ('hardware', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scanner', to='SubSync.hardware')),
            ],
        ),
    ]
