# Generated by Django 5.1.4 on 2025-03-18 09:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0019_rename_last_free_service_date_hardwareservice_free_service_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='last_payment_date',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='notification_method',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both')], default='email', help_text='Method of notification (email, SMS, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='SubSync.subscription')),
            ],
        ),
    ]
