# Generated by Django 5.1.4 on 2025-03-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0021_reminder_scheduled_task_id_resource_billing_cycle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='capacity',
        ),
    ]
