# Generated by Django 5.1.4 on 2025-03-19 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0022_remove_resource_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='hosting_type',
        ),
    ]
