# Generated by Django 5.1.4 on 2025-03-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0023_remove_resource_customers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='hosting_location',
        ),
        migrations.AlterField(
            model_name='resource',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannual', 'Biannual'), ('annual', 'Annual')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Maintenance'), ('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], max_length=20),
        ),
    ]
