# Generated by Django 5.1.7 on 2025-03-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0025_customer_billing_cycle_customer_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='subscription_cycle',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='servers',
            name='server_type',
            field=models.CharField(max_length=50),
        ),
    ]
