# Generated by Django 5.1.7 on 2025-03-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0026_remove_reminder_subscription_cycle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardwareservice',
            name='service_notes',
        ),
        migrations.AddField(
            model_name='customer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hardwareservers',
            name='hardware_server_name',
            field=models.CharField(default='df', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='hosting_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hardware_type',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Mobile Phone', 'Mobile Phone'), ('Tablet', 'Tablet'), ('Network Device', 'Network Device'), ('Air Conditioner', 'Air Conditioner'), ('on-premise server', 'on-premise server'), ('Printer', 'Printer'), ('Scanner', 'Scanner'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Maintenance', 'Maintenance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servers',
            name='server_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='softwaresubscriptions',
            name='software_id',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('pending', 'pending')], max_length=20),
        ),
        migrations.AlterField(
            model_name='utilities',
            name='consumer_no',
            field=models.IntegerField(unique=True),
        ),
    ]
