# Generated by Django 5.1.7 on 2025-03-22 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0027_remove_hardwareservice_service_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hardware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SubSync.hardware'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
