# Generated by Django 5.1.7 on 2025-03-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0028_notification_hardware_alter_resource_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwaresubscriptions',
            name='software_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
