# Generated by Django 5.1.7 on 2025-03-23 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0029_alter_softwaresubscriptions_software_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hardware_type',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='ReminderCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubSync.customer')),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reminder', to='SubSync.reminder')),
            ],
        ),
    ]
