# Generated by Django 5.1.7 on 2025-03-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0030_subscription_deleted_by_alter_hardware_hardware_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_numbers',
            field=models.TextField(blank=True, help_text='Comma-separated list of phone numbers for SMS'),
        ),
    ]
