# Generated by Django 5.1.7 on 2025-03-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0032_alter_provider_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='contact_phone',
            field=models.CharField(default='9847369352', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='website',
            field=models.URLField(),
        ),
    ]
