# Generated by Django 5.1.7 on 2025-03-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0033_alter_provider_contact_phone_alter_provider_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='category',
            field=models.CharField(choices=[('Software', 'Software'), ('Billing', 'Billing'), ('Server', 'Server'), ('Domain', 'Domain')], default='software', max_length=50),
            preserve_default=False,
        ),
    ]
