# Generated by Django 5.1.7 on 2025-03-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0034_provider_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='category',
        ),
        migrations.AddField(
            model_name='warranty',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired')], default='Active', max_length=50),
        ),
    ]
