# Generated by Django 5.1.7 on 2025-03-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0036_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
