# Generated by Django 5.1.7 on 2025-03-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0037_subscription_last_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='vender_contact',
            field=models.CharField(default='hgjh', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardware',
            name='vender_email',
            field=models.EmailField(default='a@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardware',
            name='vender_name',
            field=models.CharField(default='fdf', max_length=250),
            preserve_default=False,
        ),
    ]
