# Generated by Django 5.1.7 on 2025-03-28 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0038_hardware_vender_contact_hardware_vender_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardware',
            old_name='vender_contact',
            new_name='vendor_contact',
        ),
        migrations.RenameField(
            model_name='hardware',
            old_name='vender_email',
            new_name='vendor_email',
        ),
        migrations.RenameField(
            model_name='hardware',
            old_name='vender_name',
            new_name='vendor_name',
        ),
    ]
