# Generated by Django 5.1.7 on 2025-03-28 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0039_rename_vender_contact_hardware_vendor_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_hardware', to=settings.AUTH_USER_MODEL),
        ),
    ]
