# Generated by Django 5.1.7 on 2025-03-28 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0040_hardware_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
