# Generated by Django 5.1.7 on 2025-03-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0042_resource_deleted_at_resource_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='vendor_contact',
            field=models.CharField(max_length=15),
        ),
    ]
