# Generated by Django 5.1.7 on 2025-03-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0043_alter_hardware_vendor_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='name_specification',
            field=models.CharField(default='gy', max_length=100),
            preserve_default=False,
        ),
    ]
