# Generated by Django 5.1.7 on 2025-03-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0044_networkdevice_name_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='hardware_server_name',
            field=models.CharField(default='gdg', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_type',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Server', 'Server')], max_length=50),
        ),
        migrations.DeleteModel(
            name='HardwareServers',
        ),
    ]
