# Generated by Django 5.1.7 on 2025-03-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0045_computer_hardware_server_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='hardware_server_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
