# Generated by Django 5.1.7 on 2025-04-02 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0046_alter_computer_hardware_server_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('renewal', 'Renewal'), ('maintenance', 'Maintenance'), ('warranty', 'warranty'), ('over due', 'Over Due'), ('server break down', 'Server Break Down'), ('server_expiry', 'Server Expiry')], default='renewal', max_length=50),
        ),
        migrations.AlterField(
            model_name='remindersubscription',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_subscriptions', to='SubSync.subscription'),
        ),
    ]
