# Generated by Django 5.1.7 on 2025-04-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0047_alter_reminder_reminder_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannual', 'Biannual'), ('yearly', 'yearly')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expiring Soon', 'Expiring Soon'), ('Expired', 'Expired')], default='Active', max_length=50),
        ),
    ]
