# Generated by Django 5.1.7 on 2025-04-07 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0054_remove_historicalresource_last_updated_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalresource',
            old_name='last_payement_date',
            new_name='last_payment_date',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='last_payement_date',
            new_name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='historicalcustomer',
            name='resource',
        ),
        migrations.AddField(
            model_name='customer',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalresource',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='SubSync.customer'),
        ),
        migrations.AddField(
            model_name='resource',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='SubSync.customer'),
        ),
    ]
