# Generated by Django 5.1.7 on 2025-04-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0055_rename_last_payement_date_historicalresource_last_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubscription',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='end_date',
        ),
    ]
