# Generated by Django 5.1.7 on 2025-04-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0056_remove_historicalsubscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwareservice',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Maintenance Soon', 'Maintenance Soon'), ('Maintenance Due', 'Maintenance Due'), ('Expired', 'Expired')], default='Active', help_text='Status of the service contract', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalhardwareservice',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Maintenance Soon', 'Maintenance Soon'), ('Maintenance Due', 'Maintenance Due'), ('Expired', 'Expired')], default='Active', help_text='Status of the service contract', max_length=20),
        ),
    ]
