# Generated by Django 5.1.7 on 2025-04-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0057_hardwareservice_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareservice',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Maintenance Soon', 'Maintenance Soon'), ('Maintenance Due', 'Maintenance Due')], default='Active', help_text='Status of the service contract', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalhardwareservice',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Maintenance Soon', 'Maintenance Soon'), ('Maintenance Due', 'Maintenance Due')], default='Active', help_text='Status of the service contract', max_length=20),
        ),
    ]
