# Generated by Django 5.1.7 on 2025-04-09 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0058_alter_hardwareservice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SubSync.customer'),
        ),
    ]
