# Generated by Django 5.1.7 on 2025-04-09 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0059_notification_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='hardwareservice',
            name='hardware',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='SubSync.hardware'),
        ),
    ]
