# Generated by Django 5.1.7 on 2025-04-10 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0061_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hardware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SubSync.hardware'),
        ),
        migrations.AddField(
            model_name='reminderhardware',
            name='reminder_type',
            field=models.CharField(choices=[('warranty', 'Warranty Expiry'), ('service', 'Service Due'), ('maintenance', 'Maintenance')], default='warranty', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='reminderhardware',
            unique_together={('reminder', 'hardware', 'reminder_type')},
        ),
    ]
