# Generated by Django 5.1.4 on 2025-03-20 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubSync', '0025_customer_billing_cycle_customer_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('Inhouse', 'In-house'), ('External', 'External')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='SubSync.customer'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20),
        ),
    ]
